- name: Print parameters from parameter store
  hosts: localhost
  connection: local
  tasks:
    - name: Print parameters from parameter store
      debug: msg=" {{ {{ lookup('aws_ssm', 'Hello', region='us-east-2' ) }}"