- name: Print parameters from parameter store
  hosts: localhost
  connection: local
  tasks:
    - name: Print parameters from parameter store
      debug:
        msg: parameter- {{ lookup('amazon.aws.aws_ssm', 'test.test', region='us-eas+t-1 ' ) }}